use ABShopping

INSERT INTO Items(ItemName, Category) Values
('ULYSSES','Books'),
('THE GREAT GATSBY','Books'),
('A PORTRAIT OF THE ARTIST AS A YOUNG MAN','Books'),
('LOLITA','Books'),
('BRAVE NEW WORLD','Books'),
('THE SOUND AND THE FURY','Books'),
('CATCH-22','Books'),
('DARKNESS AT NOON','Books'),
('SONS AND LOVERS','Books'),
('THE GRAPES OF WRATH','Books'),
('UNDER THE VOLCANO','Books'),
('THE WAY OF ALL FLESH','Books'),
('1984','Books'),
('I, CLAUDIUS','Books'),
('TO THE LIGHTHOUSE','Books'),
('AN AMERICAN TRAGEDY','Books'),
('THE HEART IS A LONELY HUNTER','Books'),
('SLAUGHTERHOUSE-FIVE','Books'),
('INVISIBLE MAN','Books'),
('NATIVE SON','Books'),
('HENDERSON THE RAIN KING','Books'),
('APPOINTMENT IN SAMARRA','Books'),
('U.S.A.(trilogy)','Books'),
('WINESBURG, OHIO','Books'),
('A PASSAGE TO INDIA','Books'),
('THE WINGS OF THE DOVE','Books'),
('THE AMBASSADORS','Books'),
('TENDER IS THE NIGHT','Books'),
('THE STUDS LONIGAN TRILOGY','Books'),
('THE GOOD SOLDIER','Books'),
('ANIMAL FARM','Books'),
('THE GOLDEN BOWL','Books'),
('SISTER CARRIE','Books'),
('A HANDFUL OF DUST','Books'),
('AS I LAY DYING','Books'),
('ALL THE KINGS MEN','Books'),
('THE BRIDGE OF SAN LUIS REY','Books'),
('HOWARDS END','Books'),
('GO TELL IT ON THE MOUNTAIN','Books'),
('THE HEART OF THE MATTER','Books'),
('LORD OF THE FLIES','Books'),
('DELIVERANCE','Books'),
('A DANCE TO THE MUSIC OF TIME (series)','Books'),
('POINT COUNTER POINT','Books'),
('THE SUN ALSO RISES','Books'),
('THE SECRET AGENT','Books'),
('NOSTROMO','Books'),
('THE RAINBOW','Books'),
('WOMEN IN LOVE','Books'),
('TROPIC OF CANCER','Books'),
('THE NAKED AND THE DEAD','Books'),
('PORTNOYS COMPLAINT','Books'),
('PALE FIRE','Books'),
('LIGHT IN AUGUST','Books'),
('ON THE ROAD','Books'),
('THE MALTESE FALCON','Books'),
('PARADES END','Books'),
('THE AGE OF INNOCENCE','Books'),
('ZULEIKA DOBSON','Books'),
('THE MOVIEGOER','Books'),
('DEATH COMES FOR THE ARCHBISHOP','Books'),
('FROM HERE TO ETERNITY','Books'),
('THE WAPSHOT CHRONICLES','Books'),
('THE CATCHER IN THE RYE','Books'),
('A CLOCKWORK ORANGE','Books'),
('OF HUMAN BONDAGE','Books'),
('HEART OF DARKNESS','Books'),
('MAIN STREET','Books'),
('THE HOUSE OF MIRTH','Books'),
('THE ALEXANDRIA QUARTET','Books'),
('A HIGH WIND IN JAMAICA','Books'),
('A HOUSE FOR MR BISWAS','Books'),
('THE DAY OF THE LOCUST','Books'),
('A FAREWELL TO ARMS','Books'),
('SCOOP','Books'),
('THE PRIME OF MISS JEAN BRODIE','Books'),
('FINNEGANS WAKE','Books'),
('KIM','Books'),
('A ROOM WITH A VIEW','Books'),
('BRIDESHEAD REVISITED','Books'),
('THE ADVENTURES OF AUGIE MARCH','Books'),
('ANGLE OF REPOSE','Books'),
('A BEND IN THE RIVER','Books'),
('THE DEATH OF THE HEART','Books'),
('LORD JIM','Books'),
('RAGTIME','Books'),
('THE OLD WIVES TALE','Books'),
('THE CALL OF THE WILD','Books'),
('LOVING','Books'),
('MIDNIGHTS CHILDREN','Books'),
('TOBACCO ROAD','Books'),
('IRONWEED','Books'),
('THE MAGUS','Books'),
('WIDE SARGASSO SEA','Books'),
('UNDER THE NET','Books'),
('SOPHIES CHOICE','Books'),
('THE SHELTERING SKY','Books'),
('THE POSTMAN ALWAYS RINGS TWICE','Books'),
('THE GINGER MAN','Books'),
('THE MAGNIFICENT AMBERSONS','Books'),
('Aracetamol','Medicines'),
('Ibuprofen','Medicines'),
('Co-codamol','Medicines'),
('Codeine','Medicines'),
('Tramadol','Medicines'),
('Morphine','Medicines'),
('Diclofenac','Medicines'),
('Asprin','Medicines'),
('Naproxen','Medicines'),
('Dihydrocodeine','Medicines'),
('Oxycodone','Medicines'),
('Nefopam','Medicines'),
('Gabapentin','Medicines'),
('Fentanyl','Medicines'),
('Ketamine','Medicines'),
('Amoxicillin.','Medicines'),
('Flucloxacillin.','Medicines'),
('Meropenem','Medicines'),
('Vancomycin','Medicines'),
('Gentamycin','Medicines'),
('Clarithromycin','Medicines'),
('Co-amoxiclav','Medicines'),
('Doxycycline','Medicines'),
('Ceftazidime','Medicines'),
('Piperacillin','Medicines'),
('Ciprofloxacin','Medicines'),
('Levofloxacin','Medicines'),
('Cephalexin','Medicines'),
('Cefuroxime','Medicines'),
('Clindamycin','Medicines'),
('Trimethoprim','Medicines'),
('Nitrofurantoin','Medicines'),
('Warfarin','Medicines'),
('Rivaroxaban','Medicines'),
('Apixaban','Medicines'),
('Enoxaparin','Medicines'),
('Funderparinex','Medicines'),
('Heparin','Medicines'),
('Citalopram','Medicines'),
('Fluoxetine','Medicines'),
('Amitriptyline','Medicines'),
('Sertraline','Medicines'),
('Venlafaxine','Medicines'),
('Mirtazapine','Medicines'),
('Trazodone','Medicines'),
('Ramipril','Medicines'),
('Doxazosin','Medicines'),
('Candesartan','Medicines'),
('Losartan','Medicines'),
('Lisinopril','Medicines'),
('Atenolol','Medicines'),
('Bisoprolol','Medicines'),
('Amlodipine','Medicines'),
('Diltiazem','Medicines'),
('Nifedipine','Medicines'),
('Furosemide','Medicines'),
('Bumetanide','Medicines'),
('Spironolactone','Medicines'),
('Bendroflumethiazide','Medicines'),
('Indapamide','Medicines'),
('Amiloride','Medicines'),
('Normal Saline','Medicines'),
('Plasmalyte','Medicines'),
('Hartmanns solution','Medicines'),
('Geloplasma','Medicines'),
('Glucose','Medicines'),
('Zopiclone','Medicines'),
('Haloperidol','Medicines'),
('Lorazepam','Medicines'),
('Midazolam','Medicines'),
('Diazepam','Medicines'),
('Chlordiazepoxide','Medicines'),
('Temazepam','Medicines'),
('Phenobarbitol','Medicines'),
('Levothyroxine','Medicines'),
('Adcal','Medicines'),
('Ferrous Fumarate','Medicines'),
('Ferrous Sulphate','Medicines'),
('Multivitamins','Medicines'),
('Thiamine','Medicines'),
('Cholecalciferol','Medicines'),
('Quinine','Medicines'),
('Folic Acid','Medicines'),
('Sandoz-K','Medicines'),
('Sandoz-Phosphate','Medicines'),
('Slow sodium','Medicines'),
('Alendronic Acid','Medicines'),
('Pampers','Medicines'),
('Stayfree','Medicines'),
('Huggies','Medicines'),
('Mammy poko pants','Medicines'),
('Detol','Medicines'),
('Savlon','Medicines'),
('Volini Spray','Medicines'),
('Volini Gel','Medicines'),
('Johnson and Johnson Powder','Medicines'),
('Himilaya baby powder','Medicines'),
('Adult Pads','Medicines'),
('Dabur Baby Powder','Medicines'),
('Move Gel','Medicines'),
('Apple iPhone 12','Phones'),
('Apple iPhone 12 mini','Phones'),
('Apple iPhone 12 Pro','Phones'),
('Apple iPhone 12 Pro Max','Phones'),
('Nokia 1100','Phones'),
('Apple iPhone 6','Phones'),
('Apple iPhone 6 Plus','Phones'),
('Nokia 105','Phones'),
('Apple iPhone 6S','Phones'),
('Apple iPhone 6S Plus','Phones'),
('Apple iPhone 5S','Phones'),
('Nokia 3210','Phones'),
('Apple iPhone 7','Phones'),
('ApplePhone 7 Plus','Phones'),
('Apple iPhone 11','Phones'),
('Apple iPhone 11 Pro','Phones'),
('Apple iPhone 11 Pro Max','Phones'),
('Apple iPhone XR','Phones'),
('Apple iPhone XS','Phones'),
('Apple iPhone XS Max','Phones'),
('Nokia 6600','Phones'),
('Nokia 1200','Phones'),
('Nokia 5230','Phones'),
('Samsung E1100','Phones'),
('Apple iPhone 5','Phones'),
('Nokia 2600','Phones'),
('Motorola RAZR V3','Phones'),
('Nokia 1600','Phones'),
('Nokia 3310','Phones'),
('Apple iPhone 8','Phones'),
('Apple iPhone 8 Plus','Phones'),
('Nokia 1208','Phones'),
('Nokia 1280','Phones'),
('Nokia 6010','Phones'),
('Samsung Galaxy S III','Phones'),
('Galaxy S III Mini','Phones'),
('Samsung Galaxy S4','Phones'),
('Nokia 5130','Phones'),
('Apple iPhone X','Phones'),
('Apple iPhone 4S','Phones'),
('Motorola StarTAC','Phones'),
('Motorola C200','Phones'),
('Motorola C139','Phones'),
('Samsung Galaxy S7','Phones'),
('Galaxy S7 edge','Phones'),
('Nokia 3100','Phones'),
('Nokia 6230','Phones'),
('Apple iPhone 4','Phones'),
('Samsung Galaxy S6','Phones'),
('Galaxy S6 edge','Phones'),
('Nokia N70','Phones'),
('Samsung Galaxy S8','Phones'),
('Galaxy S8+','Phones'),
('Samsung Galaxy S II','Phones'),
('Samsung Galaxy S10','Phones'),
('Galaxy S10+','Phones'),
('Galaxy S10e','Phones'),
('Samsung Galaxy S9','Phones'),
('Galaxy S9+','Phones'),
('Nokia 2650','Phones'),
('Nokia 6300','Phones'),
('Apple iPhone 3GS','Phones'),
('Huawei P20','Phones'),
('Huawei P20 Pro','Phones'),
('Huawei P20 Lite','Phones'),
('Samsung Galaxy A10','Phones'),
('Samsung E250','Phones'),
('LG KP100','Phones'),
('Samsung Galaxy Note II','Phones'),
('Nokia 5200','Phones'),
('Xiaomi Redmi Note 8','Phones'),
('Samsung Galaxy S20','Phones'),
('Galaxy S20+','Phones'),
('Galaxy S20 Ultra','Phones'),
('Samsung Galaxy S','Phones'),
('Samsung Galaxy Grand Prime Plus','Phones'),
('Samsung Galaxy A50','Phones'),
('Apple iPhone SE','Phones'),
('Samsung Galaxy A51','Phones'),
('Samsung Galaxy A20','Phones'),
('LG Chocolate VX8500','Phones'),
('Nokia 2100','Phones'),
('Xiaomi Redmi Note 7','Phones'),
('Redmi Note 7 Pro','Phones'),
('Huawei P30','Phones'),
('Samsung Galaxy A21s','Phones'),
('Huawei Mate 10','Phones'),
('Huawei Mate 20','Phones'),
('Samsung Galaxy A01','Phones'),
('HTC Thunderbolt','Phones'),
('Huawei Mate 9','Phones'),
('Samsung Galaxy A11','Phones'),
('Samsung Galaxy J2','Phones'),
('Nokia 5610 XpressMusic','Phones'),
('Nokia 5800 XpressMusic','Phones'),
('Nokia E71','Phones'),
('Sony Ericsson K300','Phones'),
('Sony Ericsson K750','Phones'),
('Sony Ericsson W800','Phones'),
('Xiaomi Redmi Note 9 Pro','Phones'),
('Samsung Galaxy S21','Phones'),
('Galaxy S21+','Phones'),
('Galaxy S21 Ultra','Phones'),
('Motorola Droid Bionic','Phones'),
('LG Cookie (KP500)','Phones'),
('Huawei Mate 30','Phones'),
('Huawei Mate 30 Pro','Phones'),
('Samsung SGH-E700','Phones'),
('Nokia N95','Phones'),
('LG Shine','Phones'),
('Xiaomi Mi 2','Phones'),
('Samsung Galaxy Note 3','Phones'),
('LG G3','Phones'),
('Samsung Galaxy Note 8','Phones'),
('Xiaomi Redmi 6A','Phones'),
('Oppo A5','Phones'),
('Samsung Galaxy Note 9','Phones'),
('Samsung Galaxy A30','Phones'),
('Xiaomi Redmi 8A','Phones'),
('Oppo F1 Plus','Phones'),
('Xiaomi Redmi 8','Phones'),
('Samsung Galaxy J4+','Phones'),
('Samsung Galaxy J6+','Phones'),
('Samsung Galaxy Note 4','Phones'),
('Samsung Galaxy A10s','Phones'),
('Samsung Galaxy A30s','Phones'),
('Nokia N-Gage Taco','Phones'),
('LG G2','Phones'),
('Google Pixel','Phones'),
('Google Pixel XL','Phones'),
('Apple 16-Inch MacBook Pro M1 Max','Laptops'),
('Dell XPS 13','Laptops'),
('ASUS ROG Flow x13','Laptops'),
('Apple MacBook Air M1','Laptops'),
('Lenovo Yoga Slim 7i Carbon','Laptops'),
('ASUS ExpertBook B9400','Laptops'),
('Acer Nitro 5','Laptops'),
('Acer Aspire 7','Laptops'),
('MSI Pulse GL66','Laptops'),
('ASUS ROG Zephyrus G14','Laptops'),
('Lenovo Legion 7 15','Laptops'),
('ASUS ROG Strix G15 G513','Laptops'),
('MSI Pulse GL66','Laptops'),
('ASUS ROG Zephyrus M16 GU603','Laptops'),
('MSI GF65 Thin','Laptops'),
('ASUS TUF Gaming Dash F15','Laptops'),
('ASUS TUF Gaming Dash F15','Laptops'),
('Acer Predator Helios 300','Laptops'),
('Dell G7 7500','Laptops'),
('Acer Predator Triton 300','Laptops'),
('ASUS ROG Zephyrus S15 GX502','Laptops'),
('ASUS ZenBook Pro Duo UX581','Laptops'),
('ASUS ZenBook Pro Duo UX581','Laptops'),
('MSI GP65 Leopard','Laptops'),
('Acer Predator Helios 300','Laptops'),
('MSI GE66 Raider','Laptops'),
('Alienware m15 R2','Laptops'),
('Alienware m15 R3','Laptops'),
('ASUS ROG Zephyrus Duo 15','Laptops'),
('Alienware m15 R3','Laptops'),
('ASUS ROG Strix G17 G712','Laptops'),
('MSI Katana GF66','Laptops'),
('HP OMEN 16','Laptops'),
('HP Pavilion Gaming 15','Laptops'),
('HP Pavilion Gaming 15','Laptops'),
('HP Pavilion Gaming 15','Laptops'),
('HP ENVY 15','Laptops'),
('ASUS ROG Zephyrus G14','Laptops'),
('ASUS TUF Gaming F17 FX706','Laptops'),
('ASUS ROG Zephyrus G14 GA401','Laptops'),
('ASUS TUF Dash F15','Laptops'),
('ASUS TUF Gaming F17 FX706','Laptops'),
('HP OMEN 16','Laptops'),
('Alienware m15 R3','Laptops'),
('MSI GS65 Stealth Thin','Laptops'),
('ASUS ROG Zephyrus G15 GA502','Laptops'),
('MSI GF65 Thin','Laptops'),
('ASUS ROG Zephyrus G14 GA401','Laptops'),
('ASUS Zephyrus M16 GU603','Laptops'),
('ASUS TUF Gaming Dash F15','Laptops'),
('ASUS TUF Gaming Dash F15','Laptops'),
('ASUS TUF Dash F15','Laptops'),
('Acer Nitro 5','Laptops'),
('Dell G5 SE 5505','Laptops'),
('Dell G5 SE 5505','Laptops'),
('Dell G5 SE 5505','Laptops'),
('MSI GS65 Stealth Thin','Laptops'),
('Dell XPS 9700','Laptops'),
('Dell XPS 9500','Laptops'),
('ASUS ROG STRIX G15 G512','Laptops'),
('HP Pavilion Gaming 15','Laptops'),
('HP Pavilion Gaming 15','Laptops'),
('ASUS ROG STRIX G15 G512','Laptops'),
('ASUS ROG STRIX G15 G512','Laptops'),
('Dell G5 5500','Laptops'),
('Lenovo IdeaPad 3 15 Gaming','Laptops'),
('ASUS TUF Gaming F15 FX506','Laptops'),
('HP Pavilion Gaming 15','Laptops'),
('ASUS TUF Gaming F15 FX506','Laptops'),
('ASUS ROG Flow X13','Laptops'),
('MSI GF63 Thin','Laptops'),
('ASUS ROG Zephyrus G14','Laptops'),
('ASUS ROG Zephyrus G14 GA401','Laptops'),
('Lenovo Legion 5 15','Laptops'),
('Lenovo IdeaPad 3 15 Gaming','Laptops'),
('Acer Nitro 5','Laptops'),
('ASUS ROG Flow X13','Laptops'),
('MSI Summit E15','Laptops'),
('ASUS ROG Flow X13','Laptops'),
('HP ENVY 14','Laptops'),
('MSI Prestige 15','Laptops'),
('MSI GF63 Thin','Laptops'),
('MSI GF63 Thin','Laptops'),
('Lenovo Legion 5i 15','Laptops'),
('Dell G3 3500','Laptops'),
('Lenovo Legion 5 15','Laptops'),
('Lenovo IdeaPad Gaming 3i 15','Laptops'),
('HP Pavilion Gaming 15','Laptops'),
('Lenovo Legion 5i 15','Laptops'),
('Samsung Refrigerator','Appliances'),
('Bajaj Refrigerator','Appliances'),
('Goodrej Refrigerator','Appliances'),
('Phillips Refrigerator','Appliances'),
('LG Refrigerator','Appliances'),
('Whirlpool Refrigerator','Appliances'),
('Samsung Refrigerator','Appliances'),
('Videocon Refrigerator','Appliances'),
('Haier Refrigerator','Appliances'),
('Siemens Refrigerator','Appliances'),
('Goodrej Washing Machine','Appliances'),
('Phillips Washing Machine','Appliances'),
('Samsung Washing Machine','Appliances'),
('LG Washing Machine','Appliances'),
('Onida Washing Machine','Appliances'),
('Panasonic Washing Machine','Appliances'),
('Whirlpool Washing Machine','Appliances'),
('Haier Washing Machine','Appliances'),
('Haier AC','Appliances'),
('Voltas AC','Appliances'),
('Daiken AC','Appliances'),
('LG AC','Appliances'),
('Blue Star AC','Appliances'),
('Hitachi AC','Appliances'),
('Mitsubishi AC','Appliances'),
('Carrier AC','Appliances'),
('Havells Chimney','Appliances'),
('Havells Chimney','Appliances'),
('Phillips Chimney','Appliances'),
('Goodrej Chimney','Appliances'),
('Orient Chimney','Appliances'),
('Crompton Greaves Fan','Appliances'),
('Usha Fan','Appliances'),
('Orient Fan','Appliances'),
('Superfan Fan','Appliances'),
('Orbit Fan','Appliances'),
('Khaitan Fan','Appliances'),
('Havells Fan','Appliances'),
('Bajaj fan','Appliances'),
('Phillips Bulb','Appliances'),
('Syska Bulb','Appliances'),
('Bajaj Bulb','Appliances'),
('HPL Bulb','Appliances'),
('GE Bulb','Appliances'),
('Eaton Bulb','Appliances'),
('Seoul Bulb','Appliances'),
('Everlight Bulb','Appliances'),
('Sony Headphones','Appliances'),
('Sony Earphones','Appliances'),
('Apple Headphones','Appliances'),
('Apple Earphones','Appliances'),
('Sennheiser Headphones','Appliances'),
('Sennheiser Earphones','Appliances'),
('JBL Headphones','Appliances'),
('JBL Earphones','Appliances'),
('Beats Headphones','Appliances'),
('Beats Earphones','Appliances'),
('iBall Headphones','Appliances'),
('iBall Earphones','Appliances'),
('Bose Headphones','Appliances'),
('Bose Earphones','Appliances'),
('Logitech Headphones','Appliances'),
('Logitech Earphones','Appliances'),
('Boat Headphones','Appliances'),
('Boat Earphones','Appliances'),
('Audio Technica Headphones','Appliances'),
('Audio Technica Earphones','Appliances'),
('Beyerdynamic Headphones','Appliances'),
('Beyerdynamic Earphones','Appliances'),
('SkullCandy Headphones','Appliances'),
('SkullCandy Earphones','Appliances'),
('Sony TV','Appliances'),
('Micromax TV','Appliances'),
('Vu TV','Appliances'),
('Mi TV','Appliances'),
('Haier TV','Appliances'),
('Samsung TV','Appliances'),
('LG TV','Appliances'),
('Panasonic TV','Appliances'),
('Phillips TV','Appliances'),
('Onida TV','Appliances'),
('Sansui TV','Appliances'),
('Videocon TV','Appliances'),
('Canon Camera','Appliances'),
('Nikon Camera','Appliances'),
('Sony Camera','Appliances'),
('Fujifilm Camera','Appliances'),
('Panasonic Camera','Appliances'),
('Olympus Camera','Appliances'),
('Leica Camera','Appliances'),
('GoPro Camera','Appliances'),
('French Fries','Foods'),
('Soya Chaap','Foods'),
('Frozen Paratha','Foods'),
('Frozen Chapati','Foods'),
('Frozen Sweet Corn','Foods'),
('Frozen Chicken Seekh Kabab','Foods'),
('Frozen Spring Roll','Foods'),
('Frozen Chicken Popcorn','Foods'),
('Frozen Aloo Paratha','Foods'),
('Frozen Cheese Ball','Foods'),
('Frozen Chicken Tikka','Foods'),
('Frozen Veg Paratha','Foods'),
('Frozen Cutlet','Foods'),
('Frozen Idli','Foods'),
('Frozen Potato','Foods'),
('Frozen Baby Corn','Foods'),
('Veg Momos','Foods'),
('Chicken Momos','Foods'),
('Jeera Rice','Foods'),
('Malabar Paratha','Foods'),
('Kulcha','Foods'),
('Spring Rolls','Foods'),
('Breakfast Cereals','Foods'),
('Paneer Momos','Foods'),
('Thepla','Foods'),
('Indian Curries','Foods'),
('Bhakri','Foods'),
('Chicken Spring Roll','Foods'),
('Paneer Tikka','Foods'),
('Egg Rolls','Foods'),
('Chemba Puttupodi','Foods'),
('Dal Makhani','Foods'),
('Fish Fry','Foods'),
('Chicken Tikka','Foods'),
('Shahi Paneer','Foods'),
('Fish Balls','Foods'),
('Paneer Paratha','Foods'),
('Dal Tadka','Foods'),
('Palak Paneer','Foods'),
('Kadai Paneer','Foods'),
('Matar Paneer Curry','Foods'),
('Creamed Chicken','Foods'),
('Instant Noodle','Foods'),
('Vermicelli Noodle','Foods'),
('Healthy Noodle','Foods'),
('Hakka Noodle','Foods'),
('Chinese Noodle','Foods'),
('Chicken Noodles','Foods'),
('Wheat Vermicelli','Foods'),
('Cup Noodles','Foods'),
('Egg Noodle','Foods'),
('Rice Noodle','Foods'),
('Soba Noodles','Foods'),
('Falooda Mix','Foods'),
('Gulab Jamun Mix','Foods'),
('Idli Mix','Foods'),
('Millet Health Mix','Foods'),
('Dosa Mix','Foods'),
('Khaman Dhokla Mix','Foods'),
('Dosa','Foods'),
('South Indian Instant Food','Foods'),
('Instant Porridge','Foods'),
('Instant Idiyappam','Foods'),
('Vada Mix','Foods'),
('Dry Dosa','Foods'),
('Rice Sevai','Foods'),
('Instant Upma','Foods'),
('Paruppu Podi','Foods'),
('Gota Instant Mix','Foods'),
('Bajji Bonda Mix','Foods'),
('Chicken Gravy Mix','Foods'),
('Instant Pudding','Foods'),
('Rava Dosa Mix','Foods'),
('Lemon Rice Mix','Foods'),
('Instant Poha','Foods'),
('Pongal Mix','Foods'),
('Instant Paratha Mix','Foods'),
('Appam Powder','Foods'),
('Sambhar Mix','Foods'),
('Macaroni','Foods'),
('Italian Pasta','Foods'),
('Mushroom Soup Powder','Foods'),
('Vermicelli Pasta','Foods'),
('Vegetable Soup','Foods'),
('Soup Powder','Foods'),
('Tomato Soup','Foods'),
('Premix Soup','Foods'),
('Sweet Corn Soup','Foods'),
('Tomato Soup Powder','Foods'),
('Farfalle Pasta','Foods'),
('Instant Chicken Soup','Foods'),
('French Onion Soup','Foods'),
('Rice Bran','Foods'),
('Corn Flakes','Foods'),
('Cereal Flake','Foods'),
('Muesli','Foods'),
('Chocolate Flakes','Foods'),
('Millet Flakes','Foods'),
('Rolled Wheat Flakes','Foods'),
('Ragi Flakes','Foods'),
('Barley Flakes','Foods'),
('Quinoa Flakes','Foods'),
('Canned Mushroom','Foods'),
('Curd Chillies','Foods'),
('Canned Vegetables','Foods'),
('Preserved Olive','Foods'),
('Canned Bean','Foods'),
('Canned Sweet Corn','Foods'),
('Canned Baby Corn','Foods')
