use ABShopping

INSERT INTO Vendors(VendorName, State, City) values
('Appario Retail Private Ltd','Madhya Pradesh','Ujjain'),
('Cloudtail India','Karnataka','Mysore'),
('DAWNTECH ELECTRONICS','West Bengal','Midnapur'),
('Amazon Retail','Chhattisgarh','Raipur'),
('INDIAN DECOR','Sikkim','Gantok'),
('DeckUp','Meghalaya','Nongpoh'),
('IBELL POWER TOOLS','Gujarat','Ahmedabad'),
('ETrade Online','Jharkhand','Ranchi'),
('Emmbros Overseas','Jharkhand','Dhanbad'),
('HK Fab','Assam','Jorhat'),
('Darshita Etel','Assam','Guwahati'),
('EASYBUY HUB','Madhya Pradesh','Bhopal'),
('SHREEJI ETHNIC','Madhya Pradesh','Itarsi'),
('Wakefit','Sikkim','Rongpo'),
('One Assist','Assam','Tezpur'),
('Cocoblu Retail','Punjab','Jalandhar'),
('Darshita Mobiles','Meghalaya','Shillong'),
('STPL Exclusive Online','Meghalaya','Shillong'),
('TheGiftKart','Delhi','Shahjehabanad'),
('Mcaffeine','Rajasthan','Ajmer'),
('R.T.D','Kerala','Kasargod'),
('Honasa Consumer Pvt. Ltd.','Jammu and Kashmir','Srinagar'),
('Darshita Electronics','Uttar Pradesh','Sultanpur'),
('Arham World-Click','Maharashtra','Amravati'),
('Electronics Bazaar Store','Orissa','Balasore'),
('CZARTECH','Uttarakhand','Dehradun'),
('DAWNTECH ELECTRONICS','Madhya Pradesh','Ujjain'),
('Sinew Nutrition','Haryana','Gurugram'),
('The ManCompany','Goa','Panaji'),
('MuscleBlaze','Himachal Pradesh','Bilaspur'),
('K D Enterprise','Jammu and Kashmir','Gulmarg'),
('Walvia','Rajasthan','Alwar'),
('Spigen India','Uttarakhand','Haridwar'),
('OFFICIAL KEY STORE','Maharashtra','Aurangabad'),
('Yogabar','West Bengal','Midnapur'),
('Torque India','West Bengal','Jalpaiguri'),
('LUZWE Indian','Gujarat','Vadodara'),
('AMBOS','Meghalaya','Mairang'),
('uRead-Store','Telangana','Adilabad'),
('OBLIQ','Madhya Pradesh','Gwalior'),
('PAPER CUT','Punjab','Patiala'),
('QUXIS','Andhra Pradesh','Guntur'),
('Essentialsquad','Chhattisgarh','Bilaspur'),
('iBELL','Haryana','Panchkula'),
('Lullaby','Jammu and Kashmir','Kathua'),
('RENEE COSMETICS','Jharkhand','Daltonganj'),
('Repro Books-On-Demand','Delhi','Firozabad'),
('BioGrid','Uttarakhand','Rishikesh'),
('SaiTech IT Private','Orissa','Cuttack'),
('NW Noworry','Haryana','Rohtak'),
('Words N Pages','Karnataka','Mangalore'),
('DMak','Assam','Jorhat'),
('Casefactory','Punjab','Bathinda'),
('Formonix Group','Jharkhand','Bokaro Steel City'),
('Cutting EDGE','Jammu and Kashmir','Jammu'),
('Codies','Kerala','Varkala'),
('DEEJET ENTERPRISE','Goa','Panaji'),
('Asian Shoes','Punjab','Ludhiana'),
('SuperKart','West Bengal','Kharagpur'),
('KRISHNA ART','Orissa','Brahmapur'),
('Fourth Second Pvt Ltd.','Andhra Pradesh','Visakhapatnam'),
('Ninety90','Maharashtra','Nagpur'),
('R K WORLDINFOCOM P LTD','Kerala','Varkala'),
('NASULA INTERNATIONAL LLP','Tamil Nadu','Madurai'),
('TechEzy','Tamil Nadu','Coimbatore'),
('Nubilous','Orissa','Sambalpur'),
('AREESHA INDUSTRIES','Himachal Pradesh','Bilaspur'),
('Dr. Morepen-GUBB','Assam','Guwahati'),
('Ritual Beauty','Telangana','Nalgonda'),
('CZUXXY','Uttar Pradesh','Saharanpur'),
('Retailers Choice','Chandigarh','Chandighar MC'),
('Khurana Communication','Madhya Pradesh','Itarsi'),
('Keniro','Delhi','Siri'),
('Rewup','Rajasthan','Pali'),
('HEMICO','Madhya Pradesh','Jabalpur'),
('MINC-ecofashion','West Bengal','Nadia'),
('Smart Place Store','Goa','Canacona'),
('Buy More','Orissa','Brahmapur'),
('SKYTONE','West Bengal','Raiganj'),
('Shree-Hari Enterprises','Karnataka','Mangalore'),
('LITAX MART','Orissa','Balasore'),
('LEOPAX','Goa','Canacona'),
('Leader_Cycle','Meghalaya','Tura'),
('EAYIRA','Kerala','Trivantum'),
('Airtel Brand','Chhattisgarh','Korba'),
('Perfect Sales India','Chandigarh','Behlana'),
('MICROMINI','Uttarakhand','Dehradun'),
('Wellversed Health','Meghalaya','Shillong'),
('Y2V','Uttarakhand','Roorkee'),
('Jagger India','Himachal Pradesh','Chamba'),
('Spice Herbal','Punjab','Bathinda'),
('BestHerbalStore','Punjab','Bathinda'),
('Alvero','Chhattisgarh','Dhamtari'),
('FAMILY FOOTWEAR','Orissa','Balasore'),
('HSR Retail','Himachal Pradesh','Manali'),
('Wolpin','Bihar','Gaya'),
('Twonzilla','Chhattisgarh','Raigarh'),
('PEGASO','Madhya Pradesh','Jabalpur'),
('SAFERSKY','Punjab','Patiala'),
('Global Klamp','Sikkim','Namchi'),
('momox','Gujarat','Jamnagar'),
('RecycLivre','Jammu and Kashmir','Jammu'),
('Songmics','Himachal Pradesh','Bilaspur'),
('dodax-online-fr','Jammu and Kashmir','Udhampur'),
('UGREEN GROUP LIMITED','Telangana','Hyderabad'),
('La Bourse aux Livres','Uttarakhand','Mussoorie'),
('Xanho','Meghalaya','Shillong'),
('MEDIAZONE','Goa','Ponda'),
('Ponera','Kerala','Trivantum'),
('P & F','Bihar','Kishanganj'),
('Aosom','Uttarakhand','Haridwar'),
('KW-Commerce','Orissa','Balasore'),
('Ammareal','Orissa','Puri'),
('ZOverstocks','Meghalaya','Mairang'),
('Book Depository','Gujarat','Surat'),
('Stock Bureau','Jharkhand','Deoghar'),
('JacquesBooks','Maharashtra','Nashik'),
('Tuning','Kerala','Kollam'),
('pb ReCommerce','Maharashtra','Solapur'),
('MEMORYKING','Chandigarh','Khuda Alisher'),
('Groupe Dragon','Haryana','Gurugram'),
('Utopia Deals','Telangana','Adilabad'),
('JETech','Telangana','Nalgonda'),
('Werkzeugbar','Tamil Nadu','Tirunelveli'),
('Spigen EU','Orissa','Balasore'),
('SOS-Accessoire','Haryana','Panipat'),
('Toututile','Chhattisgarh','Bilaspur'),
('FR-DEUBA','Orissa','Brahmapur'),
('IDMARKET','Jharkhand','Daltonganj'),
('vidaXL','Rajasthan','Bikaner'),
('Made4Home SAS','Assam','Dibrughar'),
('BINIMEKS','Tamil Nadu','Coimbatore'),
('Get Trend.','Orissa','Puri'),
('AnkerDirect','Goa','Margao'),
('BMS','Assam','Silchar'),
('Round3','Rajasthan','Alwar'),
('worldofbooks','Telangana','Karimnagar'),
('HOME DOTCOM','Orissa','Puri'),
('COM-FOUR','Maharashtra','Amravati'),
('nagiry','Jammu and Kashmir','Jammu'),
('Weisser Berg','Telangana','Karimnagar'),
('ElectroPapa','Rajasthan','Udaipur'),
('audilo','Telangana','Karimnagar'),
('Comfort Click','Delhi','Tughlakabad'),
('JE EU Store','Andhra Pradesh','Nellore'),
('DVDMAX','Andhra Pradesh','Guntur'),
('plusdecinema','Tamil Nadu','Tiruppur'),
('XCover','Himachal Pradesh','Bilaspur'),
('rebuy recommerce GmbH','Tamil Nadu','Madurai'),
('CSL-Computer','Madhya Pradesh','Satna'),
('WOLTU GmbH','Jammu and Kashmir','Gulmarg'),
('MyMediaShop','Assam','Jorhat'),
('Grilox','Himachal Pradesh','Bilaspur'),
('Funkingdom','Goa','Mapusa'),
('lisez-plus','Assam','Guwahati'),
('123PLANTES','Goa','Panaji'),
('Fintie','Maharashtra','Aurangabad'),
('PLASTIMEA','Delhi','Shergarh'),
('1,2,3 bouquins','Chandigarh','Behlana'),
('Tech Vendor Store','Sikkim','Rongpo'),
('E-Forum','Karnataka','Manipal'),
('YURAUTTI','Tamil Nadu','Chennai'),
('Tabac du Bassigny','Andhra Pradesh','Kakinada'),
('OK PRICE','Chhattisgarh','Bilaspur'),
('AURSTORE','Goa','Ponda'),
('ADHLINE','Gujarat','Surat'),
('le projectionniste','Goa','Canacona'),
('Tinyyo Europe','Orissa','Sambalpur'),
('Everbrent','Sikkim','Pelling'),
('Vit4ever','Uttarakhand','Dehradun'),
('Pearl Diffusion','Jharkhand','Bokaro Steel City'),
('Beikell Store','Meghalaya','Mairang'),
('WilTec Wildanger Technik','Jharkhand','Daltonganj'),
('Electronic-Star','Sikkim','Gantok'),
('Cocooncenter','Assam','Guwahati'),
('Clic Musique','Orissa','Sambalpur'),
('GreatStarTools','Orissa','Cuttack'),
('La Bouquinerie','Tamil Nadu','Madurai'),
('Market-Shop62','Madhya Pradesh','Itarsi'),
('Yahee365','Meghalaya','Tura'),
('DIRECT_DVD_EU','Orissa','Rourkela'),
('RUE DE LA DROGUERIE','Assam','Jorhat'),
('M & L','Chhattisgarh','Raipur'),
('Menko Telekom','Orissa','Cuttack'),
('AllMates','Madhya Pradesh','Jabalpur'),
('AS-Discount','Meghalaya','Nongpoh'),
('JOWI','Telangana','Hyderabad'),
('Character','West Bengal','Silliguri'),
('RAREWAVES','Haryana','Hisar'),
('Benfei DirectStore','Kerala','Palakkad'),
('GRENADINE BOUTIQUE','Punjab','Mohali'),
('PRICEMASTER','Uttar Pradesh','Lucknow'),
('chapitre_libraire','Rajasthan','Bikaner'),
('ruedesprix','Karnataka','Hassan'),
('Aracase UK','Chhattisgarh','Raipur'),
('Klarstein','Karnataka','Kolar'),
('DVDMAX-FR','Jharkhand','Bokaro Steel City'),
('CABLEPELADO','Bihar','Siwan'),
('Phonillico','Telangana','Warangal'),
('Chapitre Librairie','Jharkhand','Ranchi'),
('Pharmapacks','Maharashtra','Kolhapur'),
('iServe','Haryana','Panchkula'),
('Zappos','Assam','Dibrughar'),
('Asurion','Uttarakhand','Nainital'),
('Carlyle','Madhya Pradesh','Itarsi'),
('Utopia Deals','Telangana','Adilabad'),
('topshoesUS','West Bengal','Jalpaiguri'),
('AnkerDirect','Karnataka','Udupi'),
('glenthebookseller','Jharkhand','Deoghar'),
('EPFamily Direct','Chhattisgarh','Bhilai'),
('Galactic Shop','Jammu and Kashmir','Srinagar'),
('Orva Stores','Bihar','Sharif'),
('Spreetail','Himachal Pradesh','Shimla'),
('GORILLA COMMERCE','Gujarat','Gandhinagar'),
('AilunUS','Telangana','Warangal'),
('Fintie','West Bengal','Kalna'),
('Supershieldz','Gujarat','Surat'),
('Book Depository','Madhya Pradesh','Itarsi'),
('MYBATTERYSUPPLIER','Uttar Pradesh','Ayodhya'),
('Spigen Inc','Jharkhand','Bokaro Steel City'),
('ShippedFast','Meghalaya','Mairang'),
('eSupplements','Andhra Pradesh','Kurnool'),
('uxcell','Assam','Dibrughar'),
('VerSure','Haryana','Panchkula'),
('Aserson','Meghalaya','Nongpoh'),
('6pm','Rajasthan','Kota'),
('JoyinDirect','Telangana','Hyderabad'),
('Decluttr Store','Telangana','Suryapet'),
('recommerce','Orissa','Balasore'),
('i-Deals Store','Rajasthan','Pali'),
('Mr. Pen','Gujarat','Surat'),
('Juvo+','Chandigarh','Daria'),
('TheNewMall','Haryana','Jhajjar'),
('Hippo Books','Orissa','Bhubaneswar'),
('Swanson Health Products','Telangana','Nalgonda'),
('Wiki Deals','Chandigarh','Behlana'),
('MetroDecor','Uttarakhand','Haldwani'),
('HLmedical','Telangana','Warangal'),
('Olivers Pet Care','Uttar Pradesh','Kanpur'),
('LiCB','Maharashtra','Nagpur'),
('Royal Meds','Haryana','Sonipat'),
('OxKom','Chandigarh','Behlana'),
('CPGIO','Uttarakhand','Haldwani'),
('Tech Vendor','Karnataka','Hassan'),
('TCP Global Corp','Uttar Pradesh','Gorakhpur'),
('Sports Research','Haryana','Faridabad'),
('Songmics Direct','Jharkhand','Dhanbad'),
('Common Cents Distributors','Orissa','Balasore'),
('RAREWAVES-IMPORTS','West Bengal','Kolkata'),
('River Colony Trading','Goa','Canacona'),
('LY Berditchev Co.','Uttarakhand','Nainital'),
('iHealthLabs','Bihar','Kishanganj'),
('UGREEN GROUP LIMITED','Sikkim','Rongpo'),
('Vive Health Direct','Jharkhand','Jamshedpur'),
('Woot','Jammu and Kashmir','Doda'),
('YH-Goods','Goa','Panaji'),
('Healthy Pantry','Jammu and Kashmir','Kathua'),
('Yaheetech','Punjab','Batala'),
('Impresa Products','Tamil Nadu','Salem'),
('Real Essentials','Jammu and Kashmir','Srinagar'),
('Bedsure','Maharashtra','Amravati'),
('JS Digital','Meghalaya','Tura'),
('Mr. Medical','Rajasthan','Ajmer'),
('SportingDoc','Bihar','Patna'),
('VirVentures','Uttar Pradesh','Gorakhpur'),
('Hour Loop','Bihar','Muzaffapur'),
('HiwareDirect','Assam','Tezpur'),
('Marketplace Pros','Madhya Pradesh','Gwalior'),
('Peltz Shoes','Madhya Pradesh','Satna'),
('Baleaf Sports','Andhra Pradesh','Vijayawada'),
('Monster Pets','Chhattisgarh','Dhamtari'),
('Bronson Laboratories','Rajasthan','Jaisalmer'),
('Anthonys Goods','Meghalaya','Tura'),
('My Great Goods','Andhra Pradesh','Kadapa'),
('megahitrecords','Andhra Pradesh','Nellore'),
('Libros Judios','Gujarat','Rajkot'),
('thePruneDanish','Karnataka','Mysore'),
('Vital Proteins','Orissa','Rourkela'),
('Hearthshire','Haryana','Jhajjar'),
('imagikids LLC','Kerala','Kollam'),
('VIVOSION','Maharashtra','Aurangabad'),
('SilverOnyx','Goa','Canacona'),
('K O L','Telangana','Adilabad'),
('ThriftBooks-Dallas','Tamil Nadu','Salem'),
('JDJ Trading Co','Telangana','Nalgonda'),
('BEYOND YOUR HOME','Tamil Nadu','Coimbatore'),
('The Market Space','Uttarakhand','Haldwani'),
('OTCRx4u','Jammu and Kashmir','Kathua'),
('Weiman Brands','Maharashtra','Aurangabad'),
('ThriftBooks-Phoenix','Punjab','Mohali'),
('BestSource','Rajasthan','Jaisalmer'),
('Filterbuy','Maharashtra','Pune'),
('Zulay Deals','Delhi','Lal Kot'),
('Jenson Books Inc','Rajasthan','Jaisalmer'),
('Petco','West Bengal','Malda'),
('H.VERSAILTEX','Jammu and Kashmir','Srinagar'),
('importcds','Madhya Pradesh','Indore'),
('ThriftBooks-Atlanta','Himachal Pradesh','Manali'),
('JE Products','Telangana','Hyderabad'),
('ThriftBooks-Reno','Uttar Pradesh','Meerut')
